Import("env")

import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from config_utils import load_config

pico_root = pathlib.Path(env["PROJECT_DIR"])     # RC_pico
config_dir = pico_root.parent / "config"         # RC/config

config = load_config("config", config_dir)
gpio = config["pico"]["gpio"]

lines = [
    "// AUTOGENERATED by scripts/gen_pins_header.py - DO NOT EDIT MANUALLY",
    "// Источник: RC/config/config.defaults.json + config.local.json",
    "#pragma once",
    "",
    f'static constexpr uint8_t PIN_DRIBBLER = {gpio["dribbler"]};',
    f'static constexpr uint8_t PIN_KICK_CHARGE = {gpio["kick_charge"]};',
    f'static constexpr uint8_t PIN_KICK_DISCHARGE = {gpio["kick_discharge"]};',
    f'static constexpr uint8_t PIN_ENC_A = {gpio["encA"]};',
    f'static constexpr uint8_t PIN_ENC_B = {gpio["encB"]};',
    f'static constexpr uint8_t PIN_ENC_BTN = {gpio["encBTN"]};',
    f'static constexpr uint8_t PIN_CAN_SCK = {gpio["spi_can"]["sck"]};',
    f'static constexpr uint8_t PIN_CAN_MOSI = {gpio["spi_can"]["mosi"]};',
    f'static constexpr uint8_t PIN_CAN_MISO = {gpio["spi_can"]["miso"]};',
    f'static constexpr uint8_t PIN_CAN_CS = {gpio["spi_can"]["cs"]};',
    f'static constexpr uint8_t PIN_CAN_INT = {gpio["spi_can"]["int"]};',
    f'static constexpr uint8_t PIN_IIC_SDA = {gpio["IIC"]["sda"]};',
    f'static constexpr uint8_t PIN_IIC_SCL = {gpio["IIC"]["scl"]};',
    f'static constexpr uint8_t PIN_STRIP = {gpio["strip"]};',
    f'static constexpr uint8_t PIN_ZUMMER = {gpio["zummer"]};',
    "",
]

out_path = pico_root / "include" / "pins_config.h"
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines), encoding="utf-8")
print(f"[gen_pins_header] wrote {out_path}")