; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps = 
	coryjfowler/mcp_can@^1.5.1
	fastled/FastLED@^3.10.3
platform_packages =
    toolchain-gccarmnoneeabi@~1.90301.0

[env:drive_rgb]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<drive_rgb.cpp>

[env:motor_spi0]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<motor_spi0.cpp>

[env:motor_spi1]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<motor_spi1.cpp>

[env:moving]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<moving.cpp>
lib_deps = 
    ${env.lib_deps}
	adafruit/Adafruit BNO055@^1.6.4
  	adafruit/Adafruit Unified Sensor@^1.1.15

[env:rgb_ring]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<rgb_ring.cpp>

[env:kick_test]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<kick_test.cpp>

[env:usb_sharing]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<usb_sharing.cpp>

[env:move_pos_ld]
platform = raspberrypi
board = pico
framework = arduino
build_src_filter = +<move_pos_ld.cpp>